### ISSUE TITLE
camera issue in non-headless mode while generating screenshots

### ISSUE THREAD

**Issue by piaoger** [bwasty/gltf-viewer#23]
nice to see this project will in active development again.
I found you have some improvement on camera and maybe still working on this now. 
I'd like to report this issue for track. I attached the cmdline args and one resultant screenshot which camera seems wrong.

gltf-viewer -s ./view.png -c 6 ./../KhronosGroup/glTF-Sample-Models/2.0/BrainStem/glTF-Binary/BrainStem.glb`

![view_1](https://user-images.githubusercontent.com/179429/36625073-616533fa-1953-11e8-9230-5449cdd5b0a2.jpg)

**Comment by bwasty** [comment]
Do you use macOS or have a high-DPI display? I've noticed this when I don't use `--headless` on macOS. The reason is that the pixels you request are not the ones you get (for the window), but are multiplied by something like the `devicePixelRatio` (that's how it's called in the browser).
The fix for that is easy, I just haven't gotten around to it yet.

**Comment by piaoger** [comment]
yes，i am using mac and your expain makes sense

**Comment by bwasty** [comment]
Actually the code looks good already, the problem seems to be in winit: https://github.com/tomaka/winit/issues/399.
